name: publishLab01

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  PUBLISH_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
  PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}    
    
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: ./lab-01-quizer-lib
        arguments: publish
          
